version: '3.8'
services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=apiNode
    ports:
      - 3307:3306
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
    links:
      - db


